TesteEntrevista/Controllers/VendaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TesteEntrevista.Models;

namespace TesteEntrevista.Controllers
{
    public class VendaController : Controller
    {
        private readonly AppTesteContext _context;

        public VendaController(AppTesteContext context)
        {
            _context = context;
        }

        // GET: Venda
        public async Task<IActionResult> Index([Bind("busca")] string? busca)
        {
            var venda = await _context.Venda.AsNoTracking()
                .Include(v => v.Cliente)
                .Include(v => v.Produto)
                .Where(x => string.IsNullOrEmpty(busca) || x.Cliente.nmCliente.Contains(busca) || x.Produto.dscProduto.Contains(busca))
                .ToListAsync();
            return View(venda);
        }


        public IActionResult Create()
        {
            ViewData["idCliente"] = new SelectList(_context.Cliente, "idCliente", "nmCliente");

            var produtos = _context.Produto.AsNoTracking().Select(x => new { x.idProduto, dscProduto = $"{x.dscProduto} (R$ {x.vlrUnitario:N2})" });
            ViewData["idProduto"] = new SelectList(produtos, "idProduto", "dscProduto");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("idCliente,dthVenda,idProduto,qtdVenda")] Venda venda)
        {
            ModelState.Remove("Cliente");
            ModelState.Remove("Produto");
            if (ModelState.IsValid)
            {
                venda.vlrUnitarioVenda = await _context.Produto.Where(x => x.idProduto.Equals(venda.idProduto))
                    .Select(x => x.vlrUnitario)
                    .FirstOrDefaultAsync();

                venda.vlrTotalVenda = venda.qtdVenda * venda.vlrUnitarioVenda;

                await _context.AddAsync(venda);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["idCliente"] = new SelectList(_context.Cliente, "idCliente", "nmCliente", venda.idCliente);
            ViewData["idProduto"] = new SelectList(_context.Produto, "idProduto", "dscProduto", venda.idProduto);
            return View(venda);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();

            var venda = await _context.Venda
                .AsNoTracking()
                .Include(x => x.Produto)
                .Include(x => x.Cliente)
                .Where(x => x.idVenda.Equals(id))
                .FirstOrDefaultAsync();

            if (venda == null)
                return NotFound();

            ViewData["idCliente"] = new SelectList(_context.Cliente, "idCliente", "nmCliente", venda.idCliente);
            var produtos = _context.Produto.AsNoTracking().Select(x => new { x.idProduto, dscProduto = $"{x.dscProduto} (R$ {x.vlrUnitario:N2})" });
            ViewData["idProduto"] = new SelectList(produtos, "idProduto", "dscProduto");
            return View(venda);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("idVenda,idCliente,dthVenda,idProduto,qtdVenda")] Venda venda)
        {
            if (id != venda.idVenda)
                return NotFound();

            venda.vlrUnitarioVenda = await _context.Produto.AsNoTracking()
                .Where(x => x.idProduto.Equals(venda.idProduto))
                .Select(x => x.vlrUnitario)
                .FirstOrDefaultAsync();

            venda.vlrTotalVenda = venda.qtdVenda * venda.vlrUnitarioVenda;

            ModelState.Remove("Cliente");
            ModelState.Remove("Produto");
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(venda);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VendaExists(venda.idVenda))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["idCliente"] = new SelectList(_context.Cliente, "idCliente", "nmCliente", venda.idCliente);
            var produtos = _context.Produto.AsNoTracking().Select(x => new { x.idProduto, dscProduto = $"{x.dscProduto} (R$ {x.vlrUnitario:N2})" });
            ViewData["idProduto"] = new SelectList(produtos, "idProduto", "dscProduto");
            return View(venda);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            var venda = await _context.Venda
                .Include(v => v.Cliente)
                .Include(v => v.Produto)
                .FirstOrDefaultAsync(m => m.idVenda == id);
            if (venda == null)
                return NotFound();

            return View(venda);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var venda = await _context.Venda.FindAsync(id);
            if (venda != null)
            {
                _context.Venda.Remove(venda);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VendaExists(int id)
        {
            return _context.Venda.AsNoTracking().Any(e => e.idVenda == id);
        }
    }
}

TesteEntrevista/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="author" content="João Capoani" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TesteEntrevista.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">João Capoani</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cliente" asp-action="Index">Clientes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produto" asp-action="Index">Produtos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Venda" asp-action="Index">Vendas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - João Capoani
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>